apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami4
  labels:
    app: traefiklabs
    name: whoami4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami4
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami4
    spec:
      containers:
        - name: whoami4
          image: traefik/whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami4
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami4
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami4
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - whoami4.selftaught.com.ar
    secretName: whoami4selftaughtcomar-tls
  rules:
    - host: whoami4.selftaught.com.ar
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: whoami4
                port:
                  number: 80
