---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: user@e-mail.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: password
        - name: PGADMIN_PORT
          value: "80"
        image: dpage/pgadmin4:6.15
        imagePullPolicy: IfNotPresent
        name: pgadmin
        ports:
        - containerPort: 80        
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: padmin-port
    port: 8080
    targetPort: 80
  selector:
    app: pgadmin
