apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: traefiklabs
    name: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt    
spec:
  rules:
    - host: whoami.selftaught.com.ar
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name:  whoami
                port:
                  number: 80
          # - path: /bar
          #   pathType: Exact
          #   backend:
          #     service:
          #       name:  whoami
          #       port:
          #         number: 80
          # - path: /foo
          #   pathType: Exact
          #   backend:
          #     service:
          #       name:  whoami
          #       port:
          #         number: 80