apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: backupstorage-secret-store
  namespace: velero
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-backupstorage-iprd-ue.vault.azure.net/"
      serviceAccountRef:
        name: velero

