---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backupstorage-secret
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: backupstorage-secret-store

  target:
    name: backupstorage-secret
    creationPolicy: Owner

  data:
    - secretKey: primary-access-key
      remoteRef:
        key: secret/stbackupsiprdue--PrimaryAccessKey
    - secretKey: secondary-access-key
      remoteRef:
        key: secret/stbackupsiprdue--SecondaryAccessKey