# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml

configuration:
  provider: azure
  backupStorageLocation:
    bucket: velero

initContainers:
  - name: velero-velero-plugin-for-microsoft-azure
    image: velero/velero-plugin-for-microsoft-azure:v1.5.0
    volumeMounts:
      - mountPath: /target
        name: plugins

credentials:
  useSecret: true
  existingSecret: backupstorage-secret

serviceAccount:
  server:
    create: true
    name: velero    
    labels:
      azure.workload.identity/use: "true"

extraObjects:
  - apiVersion: external-secrets.io/v1beta1
    kind: SecretStore
    metadata:
      name: backupstorage-secret-store
      namespace: velero
    spec:
      provider:
        azurekv:
          authType: WorkloadIdentity
          vaultUrl: "https://kv-backupstorage-iprd-ue.vault.azure.net/"
          serviceAccountRef:
            name: velero
  - apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: backupstorage-secret
      namespace: velero
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: SecretStore
        name: backupstorage-secret-store
      target:
        name: backupstorage-secret
        creationPolicy: Owner
      data:
        - secretKey: cloud
          remoteRef:
            key: secret/velero-credentials