# helm install velero vmware-tanzu/velero \
# --namespace <YOUR NAMESPACE> \
# --create-namespace \
# --set-file credentials.secretContents.cloud=<FULL PATH TO FILE> \
# --set configuration.provider=<PROVIDER NAME> \
# --set configuration.backupStorageLocation.name=<BACKUP STORAGE LOCATION NAME> \
# --set configuration.backupStorageLocation.bucket=<BUCKET NAME> \
# --set configuration.backupStorageLocation.config.region=<REGION> \
# --set configuration.volumeSnapshotLocation.name=<VOLUME SNAPSHOT LOCATION NAME> \
# --set configuration.volumeSnapshotLocation.config.region=<REGION> \
# --set initContainers[0].name=velero-plugin-for-<PROVIDER NAME> \
# --set initContainers[0].image=velero/velero-plugin-for-<PROVIDER NAME>:<PROVIDER PLUGIN TAG> \
# --set initContainers[0].volumeMounts[0].mountPath=/target \
# --set initContainers[0].volumeMounts[0].name=plugins
# https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml


configuration:
  provider: azure
  backupStorageLocation:
    provider: azure
    bucket: velero
    config:
      resourceGroup: rg-backups-iprd-ue
      subscriptionId: ba90edc7-0080-430e-830e-f5f222c33a0c
      storageAccount: stbackupsiprdue
  initContainers:
    - name: velero-plugin-for-azure
      image: velero/velero-plugin-for-microsoft-azure:v1.6.0
      volumeMounts:
        - mountPath: /target
          name: plugins

serviceAccount:
  server:
    create: true
    name:
    annotations:      
      azure.workload.identity/client-id: 10ec2052-e7a4-4af5-9812-ed5ed16a8048 #${APPLICATION_CLIENT_ID}
      azure.workload.identity/tenant-id: dc1d2d98-eccf-4852-92b3-130cb1192b60 #${TENANT_ID}
    labels:
      azure.workload.identity/use: "true"

podLabels:
  azure.workload.identity/use: "true"


