apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello3
spec:
  replicas: 1
  selector:
    matchLabels:
      role: hello3
  template:
    metadata:
      labels:
        role: hello3
    spec:
      containers:
      - name: hello3
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hello3
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hello.selftaught.com.ar
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: hello3